module.exports = {
    CHART_TITLE_SIZE: 18,
    CHART_TITLE_COLOR: '#0092FF',
    CHART_TITLE_WEIGHT: '400',
    
    CHART_SUBTITLE_SIZE: 16,
    CHART_SUBTITLE_COLOR: '#B6B6B6',
    CHART_SUBTITLE_WEIGHT: '400',

    CHART_CONTENT_SIZE_MD: 14,
    CHART_CONTENT_SIZE_LG: 16,
    CHART_CONTENT_SIZE_SM: 12,
    
    CHART_LEGEND_SIZE : 14
};